### ISSUE TITLE
nOT, nOB argument for tagmentation-based WGBS 

### ISSUE THREAD

**Issue by ifishlin** [dpryan79/MethylDackel#108]
Hi, I tried to analyze a tagmentation-based WGBS dataset using MethylDackel, but I was confused about the nOT, nOB arguments. In TWGBS, the first 9 bps in the head of r2 must be ignored in the methylation calling. (it's un-methylated but alignable). 

Based on the section "Alignment trimming" in the README, I thought the correct setting should be 0,0,0,9. But, I saw issue #102 ; you mentioned to ignore the first 10 bp was 10,0,0,140. (if read length is 150 bp). May I ask which one is correct? Thanks

**Comment by dpryan79** [comment]
Look at the bias plot and decide according to that. That post asked explicitly about the first 10 bases, so I answered accordingly.
