### ISSUE TITLE
the -p option about a overlapping read

### ISSUE THREAD

**Issue by gill0110** [dpryan79/MethylDackel#114]
I want to know how to set the -p option to handle overlopping reads ? 
I use MethylDackel extract for the inputfile  required by methylKit, and use the commend: 

nohup MethylDackel extract -o fa1.1 --CHG --CHH --methylKit Fana.fasta fa1.1.sort.bam >>MethylDackel.log 2>&1 &

**Comment by dpryan79** [comment]
Any value for p > 0 should properly handle overlapping portions of reads (the phred score for one of the reads is converted to 0 internally).
