### ISSUE TITLE
Min mapq option seems to be ignored / -q setting has no effect

### ISSUE THREAD

**Issue by DaGaMs** [dpryan79/MethylDackel#122]
I stumbled across this when comparing some calls on hisat-aligned data where there's a lot of mapq 1 reads. When I run my self-built (slow) methylation caller, I got different results than with MethylDackel 0.6.0. I traced this down to reads with mapq 1, which I explicitly allowed (`-q 1`) but which didn't get counted. I then started playing with the `-q` setting, and I always get the same result file no matter what number I put as the parameter! I've created [a little sample bam file](https://www.dropbox.com/s/osxz2sfouhvkh65/test.bam?dl=0). The reference is  hg38, this is simply chr1:1-100000. There are reads that should pass the flag filter with mapq 1 and 60. However, setting `-q 0` and `-q 20` produces the same output file.

I'd appreciate your help - the mapq filter is quite important for us, so I'm a bit concerned now that it doesn't work as expected...

**Comment by DaGaMs** [comment]
FWIW, my exact command line was 
```
MethylDackel extract -q 0 -p 15 -r chr1:1-100000 --cytosine_report -o test hg38_full_gatk.fa.gz test.bam
```

**Comment by DaGaMs** [comment]
Just a bump on this issue - does anyone have any clue what might be causing this, or how to fix it? It's really quite a big problem for us...

**Comment by dpryan79** [comment]
I'll look into this.

**Comment by dpryan79** [comment]
Wow, yeah, this is a definite bug. I thought I had a CI test for this!

**Comment by dpryan79** [comment]
Ah, OK, so this isn't actually a bug. In short, we check the NH auxiliary tag if it's present to ensure it's not >1, since multimappers shouldn't normally be used in BS-seq. If you have a compelling reason to use them I can add another option in to allow that, though I worry that people will shoot themselves in the foot if they do so.

**Comment by DaGaMs** [comment]
Aaahhh! OK, I would like a `keepMulti` option, even though you're obviously right that most of the time this should not be used. The reason is that I know of some projects where people are looking at repeat regions or HLAs etc, so there might be good reason to allow multi-mappers in certain circumstances.

**Comment by dpryan79** [comment]
That's a fair request, I'll see if I can get around to it this week.

**Comment by dpryan79** [comment]
@DaGaMs In 0.6.1 there is an --ignoreNH option that should do what you want :)
