### ISSUE TITLE
Chromosomes effected by methylation

### ISSUE THREAD

**Issue by emiliomastriani** [dpryan79/MethylDackel#132]
Dear all,
I have troubles to understand same data from the results. I used methyldackel as methyl extract task inside the nf-core/methylseq/bwa-meth pipeline, and it worked perfectly. I have the following open questions:

1. In the methyldackel file, there is a txt report containing a table wherever indicated indicated  strand , read , position,  nmethylated , nunmethylated, as reported below. For n methylated i saw (for example) 33 for position 1096 , it means 33 methylated sites identified if i'm right. However for the position 1096 i don't know referring to which chromosome. Please, can you tell me how to connect the methylated region to its chromosome?

 
Strand	Read	Position	nMethylated	nUnmethylated
OT	1	1	742	8
OT	2	1	1234	7
OT	1	2	1299	22
OT	2	2	1195	19
OT	1	3	1270	28
OT	2	3	1168	9
OT	1	4	1096	33
OT	2	4	1102	23

2. At the end of its execution, methyldackel produced 2 svf pictures reporting the Position along mapped read/CpG Methylation % for both strand OT/OB respectively, as reported at https://github.com/dpryan79/MethylDackel#Methylation bias plotting and correction. Also in this case, I don't understand to which chromosome every position refers.

Thank you for you support.
Dr. Mastriani Emilio

**Comment by dpryan79** [comment]
1. That appears to be the methylation bias output, which is the text version of plots like https://camo.githubusercontent.com/95b03c9e48fbc805138562571b7a326c5636ddce29b2cc62ee57e4b366040982/68747470733a2f2f7261776769742e636f6d2f64707279616e37392f4d657468796c4461636b656c2f6d61737465722f6578616d706c655f4f542e737667  I assume nf-core put the actual methylation metrics elsewhere.
2. That is all of the chromosomes, which you need to look at to know if there are portions of your reads that should be ignored.

**Comment by dpryan79** [comment]
Ask the nf-core folks where to find the actual per-base methylation metrics. They're normally named something_CpG.bedGraph, but they may have changed that.

**Comment by dpryan79** [comment]
Correct, glad things got cleared up!
