### ISSUE TITLE
mbias result is different between bismark and bwameth output

### ISSUE THREAD

**Issue by nnlrl** [dpryan79/MethylDackel#137]
Hello,
  I am doing some wgbs analysis. I find that the mbias results obtained by using different bisulfite reads aligners(bwa-meth and bismark) for the same sample are completely different. This is my command. Can you tell me what is wrong
```
# bismark
bismark  -X 700  --multicore 8 --genome_folder /path/to/genome/ --output_dir  /path/to/output/ --nucleotide_coverage --bowtie2   -1 /path/to/read1.fq.gz -2 /path/to/read2.fq.gz
# bwa-meth
bwameth.py  --reference /path/to/genome/genome.fa -t 12 
/path/to/read1.fq.gz /path/to/read2.fq.gz
```

# This is BAM output using `Bismark` and `Methyldackel mbias`
![bismark_OB](https://user-images.githubusercontent.com/53906037/184146462-0ba39f5b-03c4-45a5-b3ab-e8c786570320.svg)
![bismark_OT](https://user-images.githubusercontent.com/53906037/184146561-dae5042c-dcde-4b43-8961-55bbea6f85d0.svg)

# This is BAM output using `bwa-meth` and `Methyldackel mbias`
![bwameth_OB](https://user-images.githubusercontent.com/53906037/184146970-0f310e56-748d-4c8a-a85f-7ef728cb9d61.svg)
![bwameth_OT](https://user-images.githubusercontent.com/53906037/184146991-3e1734ae-f687-4e2b-a0ed-e08215591b29.svg)

**Comment by y9c** [comment]
Hi @nnlrl, this is quit interesting. Is it because bwa-meth filter partially converted reads? Could you share the conclusion you draw from this comparison?
