### ISSUE TITLE
Clarification on definition of "unmethylated C"

### ISSUE THREAD

**Issue by cvenney** [dpryan79/MethylDackel#140]
Hi, I was wondering if you could clarify how methylation calling works. The documentation refers to unmethylated Cs:

 "This will calculate per-base CpG metrics and output them to alignments_CpG.bedGraph, which is a standard bedGraph file with column 4 being the number of reads/read pairs with evidence for a methylated C at a given position and column 5 the equivalent for an unmethylated C."

Considering only the C position of CpGs for simplicity, does this mean that methyldackel specifically counts Cs (methylated) and Ts (unmethylated)? Or does it count Cs (methylated) and non-Cs (unmethylated)? I would guess the former but I just wanted to clarify.

Thanks in advance!

**Comment by dpryan79** [comment]
The former, it'll ignore A and G as well as T when it doesn't represent an unmethylated C.
