### ISSUE TITLE
Coverage of C sites 

### ISSUE THREAD

**Issue by jsikora93** [dpryan79/MethylDackel#141]
I run your software MetylDackel on the genome methylation data for human. I got nice input coverage of ~30-40x. The software outputs that it analyzed C sites with a mean coverage of nearly half of that. Is my understanding correct that it analyzed only data from one/each DNA strand separately and that is why I see in the output only half of the read coverage?

Best,
Jarek

**Comment by dpryan79** [comment]
Yes and no, a given pair of reads is only informative for a single strand. That is, a set of reads originating from the - strand can't give you information on a C in the + strand.
