### ISSUE TITLE
Confused regarding CTOT, CTOB. Are there suggested values?

### ISSUE THREAD

**Issue by Flope** [dpryan79/MethylDackel#151]
Hi, 
Thanks for offering this tool. 
I am a bit confused regarding the inclusion bounds. 
"Mbias" only outputs 2 plots OT and OB with suggested inclusion bounds. 
Besides OT and OB, "Extract" can also accept CTOT and CTOB. 
Are CTOT and CTOB suggestions output somewhere? 
Does the mehtylseq protocol have to include some strandedness information to make Mbias report CTOT and CTOB?
I am working with NEBNext Enzymatic Methyl-seq kit, instead of the standard bisulfate conversion. 

I first trimmed the reads based on quality, adapters,... so they may be of different lengths.
If I am understanding correctly, I should use nOT, nOB instead of OT, OB. Is that correct?

Thank you for your time and help, 
Francesc

**Comment by dpryan79** [comment]
Unless you have non-directional data where will be no CTOT (complementary to the original top) or CTOB strands. Otherwise yes they would have been output. Yes, it might be best to try the nOT and nOB options instead, depending on how the mbias output looks.

**Comment by Flope** [comment]
Thank you for taking the time.
I have different types of samples/projects. Some are very clean and I could use something like -nOB 5,148,10,148 in the example below (being more stringent than the suggested). I am just including OB for simplicity but OT are similar. 
![T98GgDNA1_mbias_OB](https://github.com/dpryan79/MethylDackel/assets/3597418/5fe13be1-02a1-4161-ba63-c6473f574aab)
Others come from older samples, probably degraded and with short insert sizes. I thought that after some fastq trimming would improve but I don't see much change. I don't even know what to do with the bottom one. 
![BIO-01-0111_mbias_OB](https://github.com/dpryan79/MethylDackel/assets/3597418/9ea847a1-d050-46cc-ae39-fd9cb1a61d3b)
![BIO-01-0332_mbias_OB](https://github.com/dpryan79/MethylDackel/assets/3597418/e673c0a7-f7d5-4c18-9401-68f8c5ad2781)

**Comment by dpryan79** [comment]
Yikes, yeah just toss that bottom one if you can.
