### ISSUE TITLE
Support for relative inclusion regions

### ISSUE THREAD

**Issue by lutsik** [dpryan79/MethylDackel#31]
In data from some non-classical protocols the existing options for defining the considered regions (--OT,--OB,--CTOT and --CTOB) are suboptimal since the length of the reads can vary. In the mbias plots this is usually seen as a gradual decrease (increase) of the methylation level, instead of a usual sharp border. An option for excluding N bases from the start/end of the read would guarantee more adequate calling.

![mbias_ot](https://cloud.githubusercontent.com/assets/10563886/19521390/c34e8388-9613-11e6-890c-ec2752db8d4f.png)

**Comment by dpryan79** [comment]
FYI, this is now implemented in the `implement31` branch. I'll get it merged in for the next release in a week or two.

**Comment by lutsik** [comment]
Hi Devon,

Many thanks! I will start testing right away.

Best regards,

Pavlo

**Comment by dpryan79** [comment]
Great! Let me know if I mucked something up :)

**Comment by dpryan79** [comment]
Sorry for the delay on this, I forgot all about it. This is now in the 0.2.0 release. As an aside, the package has now been renamed, so be aware of that when you're executing commands.

**Comment by lutsik** [comment]
Dear Devon,

Many thanks again for adding this feature. Would it be also possible to activate the respective flags for the generation and plotting of the M-bias metric? Currently there seems to be no straightforward way to check the effect.

Best regards,

Pavlo

**Comment by dpryan79** [comment]
Sure, great suggestion!

**Comment by dpryan79** [comment]
Sorry for the delay, this should now be implemented in version 0.3.0.
