### ISSUE TITLE
Add option to require flags

### ISSUE THREAD

**Issue by jdidion** [dpryan79/MethylDackel#32]
Essentially the inverse of the -F option. 

Usage example:

PileOMeth extract -f 3 ...

To require all reads to be mapped in a proper pair

**Comment by jdidion** [comment]
Now that I look at the code, I see that 0x3 is required by default. 

A -f option still might be useful for users that require other flags set.

**Comment by dpryan79** [comment]
Good suggestion, added to the to do list!

**Comment by dpryan79** [comment]
This is now implemented in the `implement32` branch. I'll get it merged in and make a new release in the next week or two.

**Comment by dpryan79** [comment]
Sorry for the delay on this, I forgot all about it. This is now in the 0.2.0 release. As an aside, the package has now been renamed, so be aware of that when you're executing commands.
