### ISSUE TITLE
MethylKit format not compatible with methRead

### ISSUE THREAD

**Issue by jdidion** [dpryan79/MethylDackel#38]
I am using the latest versions of MethylDackel (0.2.0) and MethKit (0.99.2). With the --methylKit option, MethylDackel produces files with freqC and freqT columns between [0-1]. It seems like MethylKit acutally wants these values between [0-100]. When I load the methylKit files produced by methylDackel, using methRead, the numC and numT columns of the resulting methylKitRaw objects are wrong. Here's an example.

    test<-methRead(list('test'), list('test'), treatment=0, assembly='hg19', context='CpG')
    print(test)
    > test
    methylRawList object with 1 methylRaw objects

    methylRaw object with 9 rows
    --------------
       chr start end strand coverage numCs numTs
    1 chrM    33  33      +      524     3     2
    2 chrM    34  34      -     1490     6     9
    3 chrM    61  61      +      476     3     2
    4 chrM    62  62      -      787     1     7
    5 chrM    78  78      +      544     3     2
    6 chrM    79  79      -     1225     3    10
    ...

And test looks like this (it's just the head from a MethylDackel methylKit file):

    chrBase	chr	base	strand	coverage	freqC	freqT
    chrM.33	chrM	33	F	524	0.549618	0.450382
    chrM.34	chrM	34	R	1490	0.408054	0.591946
    chrM.61	chrM	61	F	476	0.556723	0.443277
    chrM.62	chrM	62	R	787	0.111817	0.888183
    chrM.78	chrM	78	F	544	0.612132	0.387868
    chrM.79	chrM	79	R	1225	0.215510	0.784490
    chrM.80	chrM	80	F	538	0.630112	0.369888
    chrM.81	chrM	81	R	1253	0.222666	0.777334
    chrM.91	chrM	91	F	482	0.647303	0.352697

When I manually load 'test' into R and multiple the freqC and freqT columns by 100, then save it and read the new file using methRead, the numCs and numTs columns are now correct.

**Comment by jdidion** [comment]
I now see that I can manually specify the format using the methRead 'pipeline' parameter. However, it would be nice if the MethylDackel methylKit files could just be compatible with the expected format. I think this just involves multiplying the numerator by 100.0 on lines 69 and 70 of extract.c.

**Comment by dpryan79** [comment]
Oops, thanks for catching this. Can you try the `fix38` branch? If that produces the correct output then I'll make a new release tomorrow.

**Comment by jdidion** [comment]
Yep that works. Thanks!
