### ISSUE TITLE
best bisulfite treated reads aligner to choose

### ISSUE THREAD

**Issue by lmanchon** [dpryan79/MethylDackel#40]
--Hi,

which bisulfite reads aligner do you recommend to then use MethylDackel, several aligners exist:

bwa-meth: https://github.com/brentp/bwa-meth
ERNE-BS5: http://erne.sourceforge.net/
RMAPBS used in MethPipe (http://smithlabresearch.org/software/methpipe/)
Bismark (http://www.bioinformatics.babraham.ac.uk/projects/bismark/)
Bison (https://sourceforge.net/projects/dna-bison/)

thank you --

**Comment by dpryan79** [comment]
`bwa-meth` is quite good and easy to install. I wrote bison, which is also quite good but very much not easy to install. I've never used ERNE-BS5 or RMAPBS. Bismark is OK, but quite slow.

**Comment by lmanchon** [comment]
yes, i confirm bison isn't easy to install with mpi lib, is it possible to install without mpi lib ?

**Comment by dpryan79** [comment]
No, it's specifically for clusters using MPI.

**Comment by lmanchon** [comment]
ok, thanks
