### ISSUE TITLE
segfault when i tried to run this out on the output of bwameth

### ISSUE THREAD

**Issue by bwlang** [dpryan79/MethylDackel#42]
I tried to run on this small input file:

[dataset_948627.dat.zip](https://github.com/dpryan79/MethylDackel/files/836269/dataset_948627.dat.zip)

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000402d3a in isCpG (seq=0x7fffeca41010 'N' <repeats 200 times>..., pos=190780450, seqlen=<value optimized out>) at common.c:11
11	    if(*(seq+pos) == 'C' || *(seq+pos) == 'c') {
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.80.el6_3.6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt
#0  0x0000000000402d3a in isCpG (seq=0x7fffeca41010 'N' <repeats 200 times>..., pos=190780450, seqlen=<value optimized out>) at common.c:11
#1  0x0000000000404cb1 in extractCalls (config=0x7fffffffdb30) at extract.c:170
#2  0x0000000000405f00 in extract_main (argc=<value optimized out>, argv=<value optimized out>) at extract.c:674
#3  0x00000035eec1ecdd in __libc_start_main () from /lib64/libc.so.6
#4  0x0000000000402a99 in _start ()
```

**Comment by dpryan79** [comment]
I'm unable to reproduce this locally. Could it be that the fasta file you're providing to MethylDackel is in a different order than what appears in the BAM file header?

**Comment by bwlang** [comment]
Hmmm i will check

**Comment by bwlang** [comment]
Sorry I lost track of this... do you  consider it a bug if the program segfaults?

**Comment by dpryan79** [comment]
If it's not due to something like the wrong fasta file being used then yes. Even then, though, if you have a good example then the this can be reopened so that a sane error message can be returned instead.
