### ISSUE TITLE
bismark equivalent files

### ISSUE THREAD

**Issue by avilella** [dpryan79/MethylDackel#47]
Hi, I am testing MethylDackel extract on bwameth alignments. Is there an equivalent file to the `.CpG_report.txt.gz` file produced by `bismark_methylation_extractor`?

**Comment by dpryan79** [comment]
No, but if you show me an example of the report from bismark I can add that :)

**Comment by avilella** [comment]
It's got as many lines as CpGs in the genome, and looks like:

```
chr11   60077   +       0       0       CG      CGT
chr11   60078   -       0       0       CG      CGA
chr11   60088   +       0       0       CG      CGT
chr11   60089   -       0       0       CG      CGT
chr11   60365   +       0       0       CG      CGA
chr11   60366   -       0       0       CG      CGT
chr11   60941   +       0       0       CG      CGC
chr11   60942   -       0       0       CG      CGC
chr11   60979   +       0       0       CG      CGT
chr11   60980   -       0       0       CG      CGG
chr11   61016   +       0       0       CG      CGT
```

From `bismark_methylation_extractor --help`:

The genome-wide cytosine methylation output file is tab-delimited in the
following format:
==========================================================================================
<chromosome>  <position>  <strand>  <count methylated>  <count
non-methylated>  <C-context>  <trinucleotide context>

**Comment by dpryan79** [comment]
I guess something like that would be possible. Do you really need sites with no coverage?

**Comment by avilella** [comment]
Well, for reproducibility with what bismark does, it would be great to have MethylDackel spit out the same.

**Comment by dpryan79** [comment]
@avilella I've added a `--cytosine_report` option in the `getContext` branch. Feel free to give that a whirl and see if it more or less matches what bismark is producing.

**Comment by avilella** [comment]
I tried this now and it worked on my test case.
