### ISSUE TITLE
Help understanding what methyldackel is doing with this bam file

### ISSUE THREAD

**Issue by bwlang** [dpryan79/MethylDackel#48]
I’m eyeballing the methylation calls from methyldackel (Version: 0.3.0 (using HTSlib version 1.2.1) ) on my bam file ([bisulfite_test_bwameth.bam.zip](https://github.com/dpryan79/MethylDackel/files/1128462/bisulfite_test_bwameth.bam.zip)).
When I count “by eye” in IGV or samtools tview(below), I find 12 A and 49 G for one specific position (I:21312) in Neuorspora crassa.

Methyldackel produces counts of 11 methylated and 5 unmethylated
I	21311	21312	68	11	5

I thought maybe this was due to me counting both reads by eye, but I tried to avoid doing that (and the difference is too big anyway).

I also tried with some crazy options to see if things were being filtered that I didn’t appreciate:
MethylDackel  extract -D 200000 -F 0 -p 1 -q 0  --keepDupes --keepDiscordant /mnt/galaxy/data/genome/nc12/sam_indexes/nc12/nc12.fa test.bam
I	21311	21312	57	20	15
still not enough reads being considered...

Tweaking IGV to flag reads with mapq < 5  yields 9 A and 28 G in the histogram… still way different from methyldackel...

Can you help me understand what's going on?

here's the samtools tview  output in the relevant location:
```
21311
CGAT
.R..
.A..
.A..
....
....
.A..
....
A...
....
....
....
T...
....
....
.A..
....
....
.A..
....
....
....
.A..
,,,,
....
....
t,,,
....
....
.A..
,,,,
,,,,
.A..
....
....
T...
.A..
.A..
T...
....
....
....
....
....
....
T...
....
,,,,
,,,,
.A..
,a,,
,,,,
....
....
,a,,
,,,,
T...
....
,a,,
....
....
....
....
....
....
.A..
....
....
....
—
```

**Comment by dpryan79** [comment]
Once you account for overlaps and strand MethylDackel and IGV agree completely. Below are all of the reads MethylDackel finds at that position followed by the methylation call (1 is methylated, -1 unmethylated):

    NS500355:NS500355:HM273AFXX:1:21204:6581:16725 -1
    NS500355:NS500355:HM273AFXX:1:21201:23591:11583 -1
    NS500355:NS500355:HM273AFXX:1:11206:17099:3875 1
    NS500355:NS500355:HM273AFXX:1:21308:8321:20047 -1
    NS500355:NS500355:HM273AFXX:4:11609:9903:12768 1
    NS500355:NS500355:HM273AFXX:4:11609:9893:12772 1
    NS500355:NS500355:HM273AFXX:2:21305:22083:19760 1
    NS500355:NS500355:HM273AFXX:4:21404:16428:6398 1
    NS500355:NS500355:HM273AFXX:2:21103:2204:4461 -1
    NS500355:NS500355:HM273AFXX:2:21204:8916:8404 1
    NS500355:NS500355:HM273AFXX:1:21309:15084:6613 -1
    NS500355:NS500355:HM273AFXX:3:21606:18289:15785 -1
    NS500355:NS500355:HM273AFXX:4:11508:15919:16617 1
    NS500355:NS500355:HM273AFXX:2:21105:19122:16551 -1
    NS500355:NS500355:HM273AFXX:2:21201:1140:3787 1
    NS500355:NS500355:HM273AFXX:3:21402:3714:18317 1
    NS500355:NS500355:HM273AFXX:1:11207:12682:4696 -1
    NS500355:NS500355:HM273AFXX:3:11504:8193:5530 1
    NS500355:NS500355:HM273AFXX:3:21611:20314:9896 -1
    NS500355:NS500355:HM273AFXX:4:11402:20558:19514 -1
    NS500355:NS500355:HM273AFXX:1:21112:3095:17048 1
    NS500355:NS500355:HM273AFXX:2:21106:4428:12245 1
    NS500355:NS500355:HM273AFXX:2:21106:4438:12237 1
    NS500355:NS500355:HM273AFXX:3:11407:22412:4700 1
    NS500355:NS500355:HM273AFXX:2:21304:6449:19027 -1
    NS500355:NS500355:HM273AFXX:3:21512:10372:7394 -1
    NS500355:NS500355:HM273AFXX:2:11201:22948:3017 1
    NS500355:NS500355:HM273AFXX:4:11504:22220:11164 1
    NS500355:NS500355:HM273AFXX:3:21512:19043:3308 -1
    NS500355:NS500355:HM273AFXX:3:21509:7348:6882 -1
    NS500355:NS500355:HM273AFXX:4:11410:11126:12395 1
    NS500355:NS500355:HM273AFXX:4:11407:5163:2724 1
    NS500355:NS500355:HM273AFXX:4:21406:22100:9190 1
    NS500355:NS500355:HM273AFXX:1:11212:11655:11962 -1
    NS500355:NS500355:HM273AFXX:1:21101:16022:3079 1

**Comment by bwlang** [comment]
I think this is all set now - thanks!
