### ISSUE TITLE
Specific non CpG context

### ISSUE THREAD

**Issue by lshepard2154** [dpryan79/MethylDackel#54]
Hi Devon,

Forgive me if I am missing this in the documentation, but I don't seem to find an option to extract non-CpG methylation in specific context (ex: CpA, CpT rather than --CHH/--CHG). Is there any way to accomplish this with MethylDackel?

Thanks for the clarification in the documentation.

**Comment by dpryan79** [comment]
No there's no way to do that with MethylDackel. I've so rarely seen a reason to do this that I would suggest using `--cytosine_report` instead and filtering the output.
