### ISSUE TITLE
Min Depth of Coverage

### ISSUE THREAD

**Issue by agustinmora** [dpryan79/MethylDackel#60]
I want to set a minimum depth of coverage to be 0, such that all CpG sites are produced in the results, even if the values after the position are all 0. Is there an easy way to make that possible? Currently, you can't set a min depth less than one.

**Comment by dpryan79** [comment]
There's no way to do that since such sites aren't even processed by the core of MethylDackel. I'm not entirely sure what the benefit of that would be, other than making it a bit easier to assess how many uncovered sites there are.

**Comment by agustinmora** [comment]
Yeah that was the goal, thank you though
