### ISSUE TITLE
dot in the 4th column of

### ISSUE THREAD

**Issue by yij047** [dpryan79/MethylDackel#62]
I’m wondering what meaning I should make of ‘.’ that is positioned on the 4th column of the resulting bedGraph file that is generated by MethylDackel extract.

Please see some examples below. Those are selected from the one of the resulting bedGraph files.

1       3408772 3408773 .       10      1
1       3408803 3408804 .       0       9
1       3408804 3408805 .       0       10

Thanks a lot.

**Comment by dpryan79** [comment]
What was the exact command you used that produced that?

**Comment by yij047** [comment]
Just called MethylDackel extract with no arguments (just the fasta and bam).  Using the perRead branch.

**Comment by dpryan79** [comment]
I'm stumped, I'm not really sure how that's happening. Is it possible for you to subset the BAM file to just include that region and see if that reproduces the issue? Then you can post that somewhere and I can try to track this down using that.

**Comment by yij047** [comment]
Yeah thank you still. I realize there're dots in the 5th column and 6th column as well. Not sure why.

**Comment by dpryan79** [comment]
If you're able to make an example of this available please reopen so I can have a look.
