### ISSUE TITLE
methylKit-compatible output

### ISSUE THREAD

**Issue by MoutonAlice** [dpryan79/MethylDackel#63]
Hi,
I am pretty new in the RRBS world. I have a basic question. In the past I have been using Bs seeker to map and call the methylation and then I use methylKit. A collaborator told me that it would be more accurate to use bwa-meth for mapping followed by methylDackel and then methylkit for the downstream.
In bs seeker methylation call, I have been doing the call in the CpG context. I just wonder why it is not possible to have an methylkit output with the cpg context. If I use the methylkit output, does that mean that I have all the contexts included? would you rather recommend to merge context in Cpg and then transform with a bash script to a methylkit format? Many thanks for your suggestions! 
Best regards
Alice

**Comment by dpryan79** [comment]
The `--methylKit` option by default will only include Cs in a CpG context and is what it sounds like you want.
