### ISSUE TITLE
About the sam flag for methylation extract

### ISSUE THREAD

**Issue by chhylp123** [dpryan79/MethylDackel#66]
Hello, I am trying to read the source code of MethylDackel to understand the methylation extract method.

I find the function _int getStrand(bam1_t *b)_ in common.c said, "Read2, reverse comp. == OT" and "Read2, forward == OB". I cannot understand that. I guess the read2 mapped to rc strand maybe from OB, while the read2 mapped to forward strand maybe from OT.

Could you please help me to solve this problem? It will be greatly helpful to me.

**Comment by dpryan79** [comment]
Yes, that's how standard directional kits work for BS-seq.

**Comment by chhylp123** [comment]
> Yes, that's how standard directional kits work for BS-seq.

Thanks very much. I have understood this problem.

And I have another problem about the flag. I found that for single-end read from PBAT protocol, SAM flag 0 and 16 in Bismark mean that this read is mapped to the forward strand and reverse complement strand, respectively. In MethylDackel , flag 0 and flag 16 mean that the read is from OT strand and OB strand, respectively.  Is this right for PBAT reads?

**Comment by dpryan79** [comment]
It's possible that bismark has changed how it handles flags with PBAT libraries, they didn't exist when either MethylDackel or bismark were created. If you're getting the wrong results from it then let me know and make a BAM file available for me.
