### ISSUE TITLE
save the output to working folder or let the user configure the output folder

### ISSUE THREAD

**Issue by antonkulaga** [dpryan79/MethylDackel#68]
I run bs-seq pipelines with Cromwell and it causes me a lot of pain that methyldackel saves the results to the same folder as the input bam. I would like to configure the output folder

**Comment by dpryan79** [comment]
See the `-o` option, which will set the entire base filename of the output. So `-o /some/path/sample` would produce `/some/path/sample_CpG.bedGraph` and such.
