### ISSUE TITLE
threading related miscounting in mbias

### ISSUE THREAD

**Issue by bwlang** [dpryan79/MethylDackel#73]
```
for core in 1 8; do for i in `seq 1 10`; do MethylDackel mbias  --noSVG  -r contig1636 -@ $core contig1636.fa 1636_only.bam > ${core}core_rep${i};done;done
```
Every execution of the tool should produce the same output.
With 1 core it does:
```
cat 1core_* |sort |uniq | wc -l = 305
```
however with 8 cores:
```
cat 8core_* |sort |uniq | wc -l = 331
```
Interestingly - it only seems to occur near the end of reads. Here are some of the interesting lines
I don't see any problem before position 69.

```
OT	2	69	1006633219	63
OT	2	69	139	63
OT	2	69	1610612995	63
OT	2	69	1811939587	63
OT	2	69	3355443459	63
OT	2	69	4027096907	63
OT	2	70	160	57
OT	2	70	32734	57
OT	2	70	32741	57
OT	2	70	32825	57
OT	2	70	32845	57
OT	2	70	32879	57
OT	2	71	1007254735	51
OT	2	71	159	51
OT	2	71	1611234511	51
OT	2	71	1812561103	51
OT	2	71	3356064975	51
OT	2	72	139	61
OT	2	72	32713	61
OT	2	72	32720	61
OT	2	72	32824	61
OT	2	72	32858	61
OT	2	73	126	67
OT	2	73	1296579251	67
OT	2	74	1111901116	63
OT	2	74	111	63
OT	2	75	63	167
OT	2	75	63	168
OT	2	75	976705670	168
OT	2	76	11	359
OT	2	76	825309759	359
```

I'm including example data here in case that's helpful:
[contig1636_example.zip](https://github.com/dpryan79/MethylDackel/files/3069646/contig1636_example.zip)

**Comment by bwlang** [comment]
this is with MethylDackel 0.3.0

**Comment by dpryan79** [comment]
Weird, I'll have a look at this tomorrow.

**Comment by dpryan79** [comment]
I'm able to reproduce this issue locally both with your example data and a random BAM file I have sitting around. I'll try to track down the root cause and get back to you.

**Comment by dpryan79** [comment]
I tracked down the cause and have it fixed for the next release, which I'll go ahead and tag shortly.
