### ISSUE TITLE
per-read and per-CpG metrics for bs-seeker2

### ISSUE THREAD

**Issue by retrogenomics** [dpryan79/MethylDackel#74]
Hi,
I'm trying to get per-read and per-CpG metrics using bam files generated by bs-seeker2, in a similar way to the output generated by bismark ('CpG_context_xxx.txt' from bismark_methylation_extractor). It looks like this:

```
Bismark methylation extractor version v0.17.0
LIN6K:00291:01397	-	chr1	1160677	z
LIN6K:00291:01397	+	chr1	1160714	Z
LIN6K:00291:01397	+	chr1	1160728	Z
LIN6K:00291:01397	+	chr1	1160730	Z
LIN6K:00291:01397	+	chr1	1160736	Z
LIN6K:00291:01397	+	chr1	1160761	Z
LIN6K:00291:01397	+	chr1	1160804	Z
LIN6K:00291:01397	+	chr1	1160819	Z
LIN6K:00291:01397	+	chr1	1160827	Z
LIN6K:00291:01397	+	chr1	1160876	Z
LIN6K:00291:01397	+	chr1	1160884	Z
LIN6K:00291:01397	+	chr1	1160886	Z
LIN6K:00291:01397	+	chr1	1160904	Z
LIN6K:00291:01397	+	chr1	1160924	Z
LIN6K:01879:02897	+	chr1	1160714	Z
LIN6K:01879:02897	+	chr1	1160728	Z
LIN6K:01879:02897	+	chr1	1160730	Z
LIN6K:01879:02897	+	chr1	1160736	Z
LIN6K:01879:02897	+	chr1	1160761	Z
```
In other word, each read or fragment has multiple lines with the methylation status of each CpG. Is there an easy way to extract this information from the .bam files using MethylDackel ?
Thanks !

**Comment by dpryan79** [comment]
No, MethylDackel support that sort of output. What do you actually intend to use that sort of output for?

**Comment by retrogenomics** [comment]
This is to input into [methpat](http://bjpop.github.io/methpat/) for visualization purpose. Any suggestion is very welcome !

**Comment by dpryan79** [comment]
I presume the methpat authors can suggest something.
