### ISSUE TITLE
MethylDackel won't compile

### ISSUE THREAD

**Issue by mblanche** [dpryan79/MethylDackel#82]
Just cloned the latest repos

id: fd05cc154a8d833167767ce03212e7830061cd44

running make give me this:
`$ make
make -C libBigWig all
make[1]: Entering directory '/home/ubuntu/MethylDackel/libBigWig'
make[1]: *** No rule to make target 'all'.  Stop.
make[1]: Leaving directory '/home/ubuntu/MethylDackel/libBigWig'
Makefile:22: recipe for target 'libbw' failed
make: *** [libbw] Error 2`

gcc version is:
`$ gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

Any help would be appreciated

thanks

**Comment by mblanche** [comment]
Got it... just realized that libBigWig was a submodule... You should update your installation instruction to: 
`git clone --recurse-submodules https://github.com/dpryan79/MethylDackel.git`

**Comment by dpryan79** [comment]
I recommend using the most recent release instead of the master branch. I'd planned on updating the instructions with the next release :)

**Comment by dpryan79** [comment]
Hmm, I just realized that I explicitly instruct people to do exactly what you did in the readme. Sorry about that! Yes, I really should update that ASAP.

**Comment by RRebo** [comment]
Hi, just cloned from the  git clone --recurse-submodules https://github.com/dpryan79/MethylDackel.git
but running make stills gives me errors:

```
make -C libBigWig all
make[1]: Entering directory '/home/data/rrebollo/MethylDackel/libBigWig'
cc -I. -g -Wall -O3 -Wsign-compare  -c -o io.o io.c
cc -I. -g -Wall -O3 -Wsign-compare  -c -o bwValues.o bwValues.c
cc -I. -g -Wall -O3 -Wsign-compare  -c -o bwRead.o bwRead.c
cc -I. -g -Wall -O3 -Wsign-compare  -c -o bwStats.o bwStats.c
cc -I. -g -Wall -O3 -Wsign-compare  -c -o bwWrite.o bwWrite.c
ar -rcs libBigWig.a io.o bwValues.o bwRead.o bwStats.o bwWrite.o
ranlib libBigWig.a
cc -I. -g -Wall -O3 -Wsign-compare  -fpic -c -o io.pico io.c
cc -I. -g -Wall -O3 -Wsign-compare  -fpic -c -o bwValues.pico bwValues.c
cc -I. -g -Wall -O3 -Wsign-compare  -fpic -c -o bwRead.pico bwRead.c
cc -I. -g -Wall -O3 -Wsign-compare  -fpic -c -o bwStats.pico bwStats.c
cc -I. -g -Wall -O3 -Wsign-compare  -fpic -c -o bwWrite.pico bwWrite.c
cc -shared  -o libBigWig.so io.pico bwValues.pico bwRead.pico bwStats.pico bwWrite.pico  -lcurl -lm -lz
make[1]: Leaving directory '/home/data/rrebollo/MethylDackel/libBigWig'
echo '#define VERSION "0.4.0"' > version.h
cc -c -Wall -g -O3 -pthread  -IlibBigWig common.c -o common.o
common.c: In function 'getMappabilityValue':
common.c:211:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
     for(int i = 0; i<config->chromCount; i++) //loop over chromosomes
     ^
common.c:211:5: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
common.c:223:13: error: redefinition of 'i'
     for(int i = 0; i<end-start; i++)
             ^
common.c:211:13: note: previous definition of 'i' was here
     for(int i = 0; i<config->chromCount; i++) //loop over chromosomes
             ^
common.c:223:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
     for(int i = 0; i<end-start; i++)
     ^
Makefile:19: recipe for target 'common.o' failed
make: *** [common.o] Error 1
```

Any ideas would be welcome, thank you!

**Comment by dpryan79** [comment]
Which compiler is `cc` on your system? Have you tried doing what the error message says and added `-std=c11` to the flags? That is `make CFLAGS="-std=c11 -Wall -g -O3 -pthread"`?

**Comment by RRebo** [comment]
Hi!
The cc on my system is:

```
cc (Debian 4.9.2-10+deb8u1) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I changed the flags, but still got an error:

```
make -C libBigWig all
make[1]: Entering directory '/home/data/rrebollo/MethylDackel/libBigWig'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/data/rrebollo/MethylDackel/libBigWig'
echo '#define VERSION "0.4.0"' > version.h
cc -c -std=c11 -Wall -g -O3 -pthread  -IlibBigWig common.c -o common.o
In file included from common.c:1:0:
MethylDackel.h:9:1: error: unknown type name 'pthread_mutex_t'
 pthread_mutex_t positionMutex;
 ^
MethylDackel.h:10:1: error: unknown type name 'pthread_mutex_t'
 pthread_mutex_t bwMutex;
 ^
MethylDackel.h:11:1: error: unknown type name 'pthread_mutex_t'
 pthread_mutex_t outputMutex;
 ^
common.c: In function 'parseBounds':
common.c:12:5: warning: implicit declaration of function 'strdup' [-Wimplicit-function-declaration]
     char *p, *s = strdup(s2), *end;
     ^
common.c:12:19: warning: initialization makes pointer from integer without a cast
     char *p, *s = strdup(s2), *end;
                   ^
Makefile:19: recipe for target 'common.o' failed
make: *** [common.o] Error 1
```


Thanks for the help

**Comment by dpryan79** [comment]
Apparently the version of gcc you're using has a different implementation of the `-pthread` option than most systems. Try adding `#include <pthread.h>` as the first line in `MethylDackel.h`.

**Comment by embertucci** [comment]
Hello,

I am currently having a similar problem after issuing the  'make' command to compile MethylDackel (cloned from 'git clone --recurse-submodules https://github.com/dpryan79/MethylDackel.git')

`make -C libBigWig all
make[1]: Entering directory `/scratch/emb19132/RRBS_prelim/MethylDackel/libBigWig'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/scratch/emb19132/RRBS_prelim/MethylDackel/libBigWig'
echo '#define VERSION "0.4.0"' > version.h
ar -rcs libMethylDackel.a common.o bed.o svg.o pileup.o extract.o MBias.o mergeContext.o perRead.o
cc -Wall -g -O3 -pthread  -o MethylDackel common.o bed.o svg.o pileup.o extract.o MBias.o mergeContext.o perRead.o main.c libMethylDackel.a libBigWig/libBigWig.a -lm -lz -lpthread -lhts -lcurl
main.c:3:24: fatal error: htslib/hts.h: No such file or directory
 #include "htslib/hts.h"
                        ^
compilation terminated.
make: *** [MethylDackel] Error 1
`

Any suggestions on how to get around this issue? I have loaded updated versions of both gcc and htslib

**Comment by dpryan79** [comment]
@embertucci I suggest just installing via `conda`. However if you'd really like the development version then pass an appropriate `CFLAGS` to `make`:

```
make CFLAGS="-O3 -pthread -I/path/to/htslib/include" LIBS="-L/path/to/htslib/lib"
```
