### ISSUE TITLE
mbias segmentaion fault 

### ISSUE THREAD

**Issue by vanessayang0927** [dpryan79/MethylDackel#83]
Hi,
I installed **MethylDackel mbias** successfully and runed it  without error for a lot of times. 
Recently, it seemed to have a **segmentation fault** in partial sequencing data

**MethylDackel version : 0.3.0-3-g084d926 (using HTSlib version 1.2.1)
references : hg19.fa
inputdata : remove duplicates bam
code : MethylDackel mbias -@ 5 --txt  hg19.fa S1_remdup.bam S1_CpG_prefix > S1_CpG.txt**

**error：**
/opt/gridengine/default/spool/cngb-compute-f02-25/job_scripts/511819: line 8: 86244 Segmentation fault

**gdb core information**
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
[New LWP 101597]
Core was generated by `MethylDackel mbias -@'.
Program terminated with signal 11, Segmentation fault.
#0  0x00002ba8665964cd in ?? ()
"core.101597" is a core file.
Please specify an executable to debug.

**Comment by dpryan79** [comment]
Can you try the most recent version (0.4.0)?

**Comment by vanessayang0927** [comment]
Thanks for your reply, it works after using version (0.4.0).
