### ISSUE TITLE
Excluding bases from the methylation bias plot

### ISSUE THREAD

**Issue by ToMatschulla** [dpryan79/MethylDackel#84]
Hi, 
I have a methylation bias plot based on merged alignments from paired and single end reads. Now i want to exclude some bases in the middle of the alignments, because the paired end dataset make bias in the center. 
Is it possible to do that?

Thanks for your help.

**Comment by dpryan79** [comment]
No, that's possible with MethylDackel. I encourage your to run the unmerged reads through instead.

**Comment by ToMatschulla** [comment]
How can I merge them afterwards for downstream analysis, e.g. to get fractional information?

**Comment by dpryan79** [comment]
You shouldn't need to merge them, MethylDackel understands that paired-end reads can overlap and will handle that appropriately.

**Comment by ToMatschulla** [comment]
But I have to merge due to low sequencing depth.

**Comment by dpryan79** [comment]
Merging won't help you with that.

**Comment by ToMatschulla** [comment]
My reads per sample, e.g. wildtype are not so high, so I thought merging them would give me a better overall coverage of the genome, not?

**Comment by dpryan79** [comment]
If your coverage is low the only solution is to sequence higher. Concatenating the mates into a single file will just mislead downstream programs about your actual coverage and yield incorrect results.

**Comment by ToMatschulla** [comment]
OK, thank you for helping.
