### ISSUE TITLE
License undeclared

### ISSUE THREAD

**Issue by rekado** [dpryan79/MethylDackel#85]
Hello,

I just packaged MethylDackel for GNU Guix, but noticed that the source code does not mention any license for the code.  Could you please attach a license notice if this is free software?

Thanks!

~~ Ricardo

**Comment by dpryan79** [comment]
Oops, I'm surprised no one has mentioned that! I've just added a copy of the MIT license and I'll make mention of that in the readme as well. Thanks for pointing this out and for making a Guix package!

**Comment by rekado** [comment]
Excellent, thank you very much!
