### ISSUE TITLE
default extract flags incompatible with RRBS

### ISSUE THREAD

**Issue by rmvpaeme** [dpryan79/MethylDackel#90]
With RRBS data, removing PCR duplicates is advised against (because default PCR duplicate removal strategies can't distinguish a real PCR duplicate from an MspI digested fragment). 

However, if the samples are sequenced on a pattern flow cell (Hiseq/Novaseq), optical duplicates can arise and it is desirable to remove these, while keeping the other reads marked as "PCR" duplicates.

I remove optical duplicates with Picard, which flags all duplicates (PCR + optical duplicates). In order to obtain correct methylation calls `--keepDupes` should be specified after specifying the option`REMOVE_SEQUENCING_DUPLICATES=true TAGGING_POLICY=OpticalOnly` in Picard MarkDuplicates.

**Comment by dpryan79** [comment]
That's quite reasonable for RRBS. I usually remove optical duplicates with clumpify from BBMap, but picard should work too. I can add a line onto the readme about RRBS if it's helpful, as is I mostly work with WGBS.

**Comment by dpryan79** [comment]
I've added mention of this to the README, thanks!
