### ISSUE TITLE
MethylDackel mbias: Segmentation fault (core dumped) on CentOS 8.0

### ISSUE THREAD

**Issue by luuloi** [dpryan79/MethylDackel#93]
I run this command on CentOS 8.0

MethylDackel mbias hg38.fa test.sorted.bam test.sorted.bam.mbias

Then the error "Segmentation fault (core dumped)" occurs. We think the segmentation fault is coming from program getMappabilityValue in common.c file. The config->chromCount value is positive, but config->chromNames are not set. Could you please help me on this issue?

Thank you for your help.

**Comment by dpryan79** [comment]
My presumption is that the fasta file has chromosome names that don't match what was used for alignment, but post the BAM file somewhere (and tell me where you got the fasta file) and I can have a look.

**Comment by abcosta** [comment]
Hi.
I am currently facing the same problem. I am using MethylDackel 0.5.0 (using HTSlib 1.9) on linux.
I am working with stickleback (reference genome from Glazer et al. 2015) and my samples were aligned with BWA-meth and sorted and indexed with samtools. The chromosome names are written as chrI, chrII, etc.
I'd be interested in knowing the solution for this issue.
Thanks!

**Comment by luuloi** [comment]
Hi @dpryan79,

I had sent you the link for bam and fastq files. 
Thanks!

**Comment by dpryan79** [comment]
Sorry for the delay, it's been a busy week on my end. I've downloaded the files from @abcosta and can't reproduce the issue (I've sent the SVG images back).

@luuloi I'm downloading the files you were working on now and will have a look.

**Comment by dpryan79** [comment]
I should note that I'm using MethylDackel 5.0.0 from Conda on an Ubuntu system. I do have access to a CentOS 7 (or maybe 8, I'd have to check) system, so I can try both of these datasets there as well if needed.

**Comment by dpryan79** [comment]
@luuloi I downloaded hg38 from UCSC and added a fake "lambda" sequence to it. After that I don't get a segfault (I would otherwise, though there's an error message beforehand). 

@abcosta Were you using centos 8 too?

**Comment by abcosta** [comment]
Thank you for checking on it!
I am using MethylDackel 0.5.0 on a Ubuntu too. I installed from conda as well using:

conda install -c bioconda methyldackel 

I haven't indexed the reference fasta file before. I just did it after your email ("samtools faidx reference.fa"), generating the .fai file, but I still got the same message. 
It's really weird, so I am wondering: Should I try to reinstall the MethylDackel again?
Did you use a different command to install it from conda?

Thanks again!

**Comment by dpryan79** [comment]
@abcosta Can you try reinstalling with `conda install -c conda-forge -c bioconda methyldackel`? We (Bioconda) use conda-forge for many dependencies, so it's possible that without including it some deprecated incompatible dependency from Bioconda is getting pulled in.

It's very odd that it's extract but not perform the mbias computation. They should be linking to all of the same things.

**Comment by luuloi** [comment]
Hi @dpryan79: I did add the lambda sequence to reference human genome hg38 but the error still
samtools faidx -n 100 hg38.fa lambda | head 
>lambda
GGGCGGCGACCTCGCGGGTTTTCGCTATTTATGAAAATTTTCCGGTTTAAGGCGTTTCCGTTCTTCTTCGTCATAACTTAATGTTTTTATTTAAAATACC
CTCTGAAAAGAAAGGAAACGACAGGTGCTGAAAGCGAGGCTTTTTGGCCTCTGTCGTTTCCTTTCTCTGTTTTTGTCCGTGGAATGAACAATGGAAGTCA
ACAAAAAGCAGCTGGCTGACATTTTCGGTGCGAGTATCCGTACCATTCAGAACTGGCAGGAACAGGGAATGCCCGTTCTGCGAGGCGGTGGCAAGGGTAA
TGAGGTGCTTTATGACTCTGCCGCCGTCATAAAATGGTATGCCGAAAGGGATGCTGAAATTGAGAACGAAAAGCTGCGCCGGGAGGTTGAAGAACTGCGG
CAGGCCAGCGAGGCAGATCTCCAGCCAGGAACTATTGAGTACGAACGCCATCGACTTACGCGTGCGCAGGCCGACGCACAGGAACTGAAGAATGCCAGAG
ACTCCGCTGAAGTGGTGGAAACCGCATTCTGTACTTTCGTGCTGTCGCGGATCGCAGGTGAAATTGCCAGTATTCTCGACGGGCTCCCCCTGTCGGTGCA
GCGGCGTTTTCCGGAACTGGAAAACCGACATGTTGATTTCCTGAAACGGGATATCATCAAAGCCATGAACAAAGCAGCCGCGCTGGATGAACTGATACCG
GGGTTGCTGAGTGAATATATCGAACAGTCAGGTTAACAGGCTGCGGCATTTTGTCCGCGCCGGGCTTCGCTCACTGTTCAGGCCGGAGCCACAGACCGCC
GTTGAATGGGCGGATGCTAATTACTATCTCCCGAAAGAATCCGCATACCAGGAAGGGCGCTGGGAAACACTGCCCTTTCAGCGGGCCATCATGAATGCGA

MethylDackel mbias hg38.fa $INPUT $OUTPUT/${Lane}.MD.bias
Segmentation fault

**Comment by xuefei6600** [comment]
#99 
# <font face="ForestGreen">I have solved the problem</font>
##  miniconda2
>if you use conda，you can :
```shell
/miniconda2/bin/conda install -y methyldackel htslib=1.9
```

## Dockerfile
>if you need use docker,this is a Dockerfile 
```Dockerfile
FROM debian:latest
MAINTAINER xuefei <710681482@qq.com>

# Miniconda2 install
COPY Miniconda2-latest-Linux-x86_64.sh /
RUN /bin/bash /Miniconda2-latest-Linux-x86_64.sh -b -p /miniconda2
RUN /miniconda2/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
RUN /miniconda2/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
RUN /miniconda2/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
RUN /miniconda2/bin/conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
RUN /miniconda2/bin/conda config --set show_channel_urls yes
RUN rm -f /Miniconda2-latest-Linux-x86_64.sh
RUN /miniconda2/bin/conda install -y methyldackel htslib=1.9
ENV PATH /miniconda2/bin:$PATH
```

## I guess the most important reason is
Methyldackel needs to rely on a c++ library htslib and the version should be `htslib=1.9`. (I tried htslib=1.10 and failed)
